# Generated by Django 5.1.2 on 2024-12-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenslista',
            name='listaCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista', to='shoppinglist.listacompra'),
        ),
    ]
