# Generated by Django 5.1.2 on 2024-11-01 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_remove_itenslista_preco_unitario_itenslista_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listacompra',
            name='data_criacap',
        ),
        migrations.AddField(
            model_name='listacompra',
            name='data_criacao',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
